crud_mvc_plus_report/Controllers/AssigmentFormsModuleController.cs
using crud_mvc_plus_report.Models;
using DataAccess;
using Domain.Class;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace crud_mvc_plus_report.Controllers
{
    public class AssigmentFormsModuleController : Controller
    {
        ApplicationContext db = new ApplicationContext();
        
        // GET: AssigmentFormsModule
        public ActionResult Index()
        {


            //Inner Join
            //var query = from a in db.Modules
            //            join b in db.AssigmentsFormsModule on a.ModuleId equals b.ModuleId
            //            join c in db.Forms on b.FormId equals c.FormId
            //            select new ModuleForms()
            //            {
            //                NameForm = c.Name,
            //                NameModule = a.Name
            //            };

            //Left Join de Modules sin Forms
            var query = from a in db.Modules
                        join b in db.AssigmentsFormsModule on a.ModuleId equals b.ModuleId
                        into AsigModules
                        from b in AsigModules.DefaultIfEmpty()
                        join c in db.Forms on b.FormId equals c.FormId into AsigForm
                        from c in AsigForm.DefaultIfEmpty()
                        select new ModuleForms()
                        {
                            AssigmentId = b == null ? 0 : b.AssigmentId,
                            FormId = b == null ? 0 : b.FormId,
                            NameForm = b == null ? "No Form": c.Name,
                            NameModule = a.Name,
                            ModuleId = a.ModuleId
                        }
                        ;


            return View(query);
        }

        // GET: AssigmentFormsModule/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AssigmentFormsModule/Create
        public ActionResult Create()
        {
            ViewBag.Modules = GetModuleDropDown();
            ViewBag.Forms = GetFormDropDown();

            return View();
        }

        // POST: AssigmentFormsModule/Create
        [HttpPost]
        public ActionResult Create(AssigmentFormsModule moduleForm)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AssigmentFormsModule/Edit/5
        public ActionResult Edit(int id)
        {
            //ModuleForms query = (from a in db.AssigmentsFormsModule
            //                    where a.AssigmentId.Equals(id)
            //                    select new ModuleForms()
            //                    {
            //                        AssigmentId = a.AssigmentId,
            //                        ModuleId = a.ModuleId,
            //                        FormId = a.FormId
            //                    }).FirstOrDefault();

            var query = db.AssigmentsFormsModule.Find(id);

            ViewBag.Modules = GetModuleDropDown();
            ViewBag.Forms = GetFormDropDown();

            return View(query);
        }

        // POST: AssigmentFormsModule/Edit/5
        [HttpPost]
        public ActionResult Edit(AssigmentFormsModule moduleForm)
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                {
                    return View();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AssigmentFormsModule/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AssigmentFormsModule/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public List<SelectListItem> GetModuleDropDown()
        {
            var items = db.Modules.Select(
               c => new SelectListItem()
               {
                   Text = c.Name,
                   Value = c.ModuleId.ToString()
               }).ToList();
            return items;
        }

        public List<SelectListItem> GetFormDropDown()
        {
            var items = db.Forms.Select(
               c => new SelectListItem()
               {
                   Text = c.Name,
                   Value = c.FormId.ToString()
               }).ToList();
            return items;
        }
    }
}

crud_mvc_plus_report/Views/AssigmentFormsModule/Create.cshtml
@model Domain.Class.AssigmentFormsModule

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Ajax.BeginForm("Create","AssigmentFormsModule",
    new AjaxOptions { HttpMethod="POST", OnSuccess="onAjaxRequestSuccess"},
    new { @id= "AjaxFormId",@class="form-horizontal", role="form"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ModuleForms</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.Label("Module", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ModuleId, ViewBag.Modules as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Form", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FormId, ViewBag.Forms as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FormId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    function onAjaxRequestSuccess() {
        console.log("onAjaxRequestSuccess");
    }
</script>

crud_mvc_plus_report/Views/AssigmentFormsModule/Edit.cshtml
@model Domain.Class.AssigmentFormsModule

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ModuleForms</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model=> model.AssigmentId)
        <div class="form-group">
            @Html.Label("Module", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ModuleId, ViewBag.Modules as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Form", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model=>model.FormId)
                @*@Html.DropDownListFor(model => model.FormId, ViewBag.Forms as IEnumerable<SelectListItem>, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.FormId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

crud_mvc_plus_report/Views/AssigmentFormsModule/Index.cshtml
@model IEnumerable<crud_mvc_plus_report.Models.ModuleForms>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameModule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameForm)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NameModule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameForm)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.AssigmentId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.AssigmentId })
        </td>
    </tr>
}

</table>